version: '3.5'

services:
  mysql:
    image: mysql/mysql-server:5.7.21
    volumes:
      - /opt/mysql_data:/var/lib/mysql
    ports:
      - "3311:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=ptt
      - MYSQL_PASSWORD=ptt

  payara:
    image: payara/server-full:181
    volumes:
      - /usr/share/java/sqlconnector/:/glassfish/domains/domain1
    ports:
      - "8085:8080"
      - "4853:4848"
    links:
      - mysql:mysql
    depends_on:
      - mysql